# Generated by Django 4.0.3 on 2023-01-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audios',
            name='description',
        ),
        migrations.AddField(
            model_name='audios',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
